In [ ]:
import requests
from bs4 import BeautifulSoup
import random

In [ ]:
user_agents = [
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
    'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15',
]

headers = {
    'User-Agent': random.choice(user_agents),
    'Accept-Language': 'en-US,en;q=0.9',
}

main_url = "https://magicroll.ru/tyumen"

def parse_url(url, headers):
  page = requests.get(url, headers=headers)
  page.encoding = 'utf-8'
  if page.status_code == 200:
    print(f"...Страница {url} доступна...")
  return page

def parse_category(menu_link):
  menu_page = parse_url(menu_link, headers)
  soup = BeautifulSoup(menu_page.text, "html.parser")
  item_links = []
  for item in soup.find_all("a", class_ = "Card_card__WC5yV Card_plated__y6g_V Card_emptyTags__mBTn5 undefined"):
    item_link = item.get("href")
    item_links.append(item_link)
  return item_links

In [ ]:
main_page = parse_url(main_url, headers)
soup = BeautifulSoup(main_page.text, "html.parser")

menu_links = []
for block in soup.find_all("a", class_ ="-m-1 p-1 transition-all hover:text-primary"):
  category_link = block.get("href")
  menu_links.append("https://magicroll.ru" + category_link)

...Страница https://magicroll.ru/tyumen доступна...

In [ ]:
all_links = []
for link in menu_links:
  item_links = parse_category(link)
  all_links = all_links + item_links

all_links = ["https://magicroll.ru" + link for link in all_links]

...Страница https://magicroll.ru/tyumen/rolly доступна...
...Страница https://magicroll.ru/tyumen/rolly-tempura доступна...
...Страница https://magicroll.ru/tyumen/rolly-zapechionnye доступна...
...Страница https://magicroll.ru/tyumen/sety доступна...
...Страница https://magicroll.ru/tyumen/rolly-maki доступна...
...Страница https://magicroll.ru/tyumen/onigiri доступна...
...Страница https://magicroll.ru/tyumen/poke-i-salaty доступна...
...Страница https://magicroll.ru/tyumen/zakuski доступна...
...Страница https://magicroll.ru/tyumen/supy доступна...
...Страница https://magicroll.ru/tyumen/goriachee-i-vok доступна...
...Страница https://magicroll.ru/tyumen/detskoe-meniu доступна...
...Страница https://magicroll.ru/tyumen/deserty доступна...
...Страница https://magicroll.ru/tyumen/molochnye-kokteili доступна...
...Страница https://magicroll.ru/tyumen/napitki доступна...
...Страница https://magicroll.ru/tyumen/dopolneniia доступна...
...Страница https://magicroll.ru/tyumen/sertifikaty доступна...

In [ ]:
def get_item_info(item_link):
  try:
    item_page = parse_url(item_link, headers)
    soup = BeautifulSoup(item_page.text, "html.parser")
    name = soup.find_all("h1")[0].text
    try:
      descr = soup.find_all("p")[0].text
    except:
      descr = ""
    nutrition_facts = []
    for i in soup.find_all(class_="inline-flex items-center transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 whitespace-nowrap rounded-2sm bg-muted px-4 py-2 text-xs font-semibold text-foreground"):
      nutrition_facts.append(i.text)
    print(f"{name} собран")
    return name, descr, nutrition_facts
  except:
    print(f"{url} не содержит информации о товаре")
    pass

In [ ]:
data = pd.DataFrame(columns = ["name", "description", "nutrition_facts", "url"])
for item_link in all_links:
  name, descr, nutrition_facts = get_item_info(item_link)
  df = pd.DataFrame(
    {
          "name" : name,
          "description" : descr,
          "nutrition_facts": nutrition_facts,
          "url" : item_link
      }
  )
  data = pd.concat([data, df])

...Страница https://magicroll.ru/tyumen/rolly/roll-filadelfiia-lait доступна...
Ролл Филадельфия лайт собран
...Страница https://magicroll.ru/tyumen/rolly/roll-kaliforniia-s-krevetkoi доступна...
Ролл Калифорния с креветкой собран
...Страница https://magicroll.ru/tyumen/rolly/roll-kaliforniia-so-snezhnym-krabom доступна...
Ролл Калифорния со снежным крабом собран
...Страница https://magicroll.ru/tyumen/rolly/roll-losos-avokado доступна...
Ролл Лосось Авокадо собран
...Страница https://magicroll.ru/tyumen/rolly/roll-filadelfiia доступна...
Ролл Филадельфия собран
...Страница https://magicroll.ru/tyumen/rolly/roll-s-krevetkoi-i-avokado доступна...
Ролл с Креветкой и авокадо собран
...Страница https://magicroll.ru/tyumen/rolly/roll-kaliforniia-s-lososem доступна...
Ролл Калифорния с лососем собран
...Страница https://magicroll.ru/tyumen/rolly/roll-karamelnaia-filadelfiia доступна...
Ролл Карамельная Филадельфия собран
...Страница https://magicroll.ru/tyumen/rolly-tempura/roll-kaliforniia-tempura доступна...
Ролл Калифорния темпура собран
...Страница https://magicroll.ru/tyumen/rolly-tempura/roll-siake-frai доступна...
Ролл Сяке Фрай  собран
...Страница https://magicroll.ru/tyumen/rolly-tempura/roll-chiken-fri доступна...
Ролл Чикен Фри собран
...Страница https://magicroll.ru/tyumen/rolly-tempura/roll-tempura-losos-avokado доступна...
Ролл Темпура Лосось Авокадо собран
...Страница https://magicroll.ru/tyumen/rolly-tempura/roll-san-khose-tempura доступна...
Ролл Сан-Хосе темпура собран
...Страница https://magicroll.ru/tyumen/rolly-tempura/roll-tempura-s-krevetkoi-i-avokado доступна...
Ролл Темпура с Креветкой и авокадо  собран
...Страница https://magicroll.ru/tyumen/rolly-zapechionnye/roll-zapechennyi-krab доступна...
Ролл Запеченный краб собран
...Страница https://magicroll.ru/tyumen/rolly-zapechionnye/roll-vulkan-zapechennyi доступна...
Ролл Вулкан Запеченный  собран
...Страница https://magicroll.ru/tyumen/rolly-zapechionnye/roll-zapechennyi-losos доступна...
Ролл Запеченный лосось собран
...Страница https://magicroll.ru/tyumen/rolly-zapechionnye/roll-san-khose-zapechennyi доступна...
Ролл Сан-Хосе Запеченный  собран
...Страница https://magicroll.ru/tyumen/rolly-zapechionnye/roll-zapechennyi-teriiaki-losos-v-tobiko доступна...
Ролл Запеченный терияки лосось в тобико собран
...Страница https://magicroll.ru/tyumen/rolly-zapechionnye/roll-tsezar-iz-pechi доступна...
Ролл Цезарь из печи собран
...Страница https://magicroll.ru/tyumen/rolly-zapechionnye/zapechennyi-roll-losos-avokado доступна...
Запеченный ролл Лосось Авокадо  собран
...Страница https://magicroll.ru/tyumen/sety/set-chiken-24sht доступна...
Сет Чикен |24шт собран
...Страница https://magicroll.ru/tyumen/sety/set-top-losos-32sht доступна...
Сет Топ лосось |32шт собран
...Страница https://magicroll.ru/tyumen/sety/set-1-1-16-sht доступна...
Сет 1+1 |16 шт собран
...Страница https://magicroll.ru/tyumen/sety/set-bez-povoda-12-sht доступна...
Сет Без повода |12 шт собран
...Страница https://magicroll.ru/tyumen/sety/set-slavnyi-malyi-12sht доступна...
Сет Славный малый |12шт собран
...Страница https://magicroll.ru/tyumen/sety/set-osobyi доступна...
Сет Особый собран
...Страница https://magicroll.ru/tyumen/sety/set-maki-32sht доступна...
Сет Маки |32шт собран
...Страница https://magicroll.ru/tyumen/sety/set-klassik-24sht доступна...
Сет Классик |24шт собран
...Страница https://magicroll.ru/tyumen/sety/set-non-stop-24sht доступна...
Сет Нон Стоп |24шт собран
...Страница https://magicroll.ru/tyumen/rolly-maki/set-maki-32-sht доступна...
Сет Маки |32 шт  собран
...Страница https://magicroll.ru/tyumen/rolly-maki/roll-maki-ogurets доступна...
Ролл Маки огурец собран
...Страница https://magicroll.ru/tyumen/rolly-maki/roll-maki-losos доступна...
Ролл Маки лосось собран
...Страница https://magicroll.ru/tyumen/rolly-maki/roll-maki-chuka доступна...
Ролл Маки Чука собран
...Страница https://magicroll.ru/tyumen/rolly-maki/roll-maki-avokado доступна...
Ролл Маки авокадо собран
...Страница https://magicroll.ru/tyumen/rolly-maki/roll-maki-kuritsa доступна...
Ролл Маки курица собран
...Страница https://magicroll.ru/tyumen/rolly-maki/roll-maki-syr доступна...
Ролл Маки сыр собран
...Страница https://magicroll.ru/tyumen/rolly-maki/roll-maki-ugor доступна...
Ролл Маки угорь собран
...Страница https://magicroll.ru/tyumen/onigiri/onigiri-s-krevetkoi-i-avokado доступна...
Онигири с креветкой и авокадо собран
...Страница https://magicroll.ru/tyumen/onigiri/onigiri-s-kuritsei-tsezar доступна...
Онигири с курицей цезарь собран
...Страница https://magicroll.ru/tyumen/poke-i-salaty/poke доступна...
Поке собран
...Страница https://magicroll.ru/tyumen/zakuski/naggetsy доступна...
Наггетсы собран
...Страница https://magicroll.ru/tyumen/zakuski/kurinye-palochki доступна...
Куриные палочки собран
...Страница https://magicroll.ru/tyumen/zakuski/kartofel-fri доступна...
Картофель Фри собран
...Страница https://magicroll.ru/tyumen/zakuski/krevetki-tempura доступна...
Креветки темпура собран
...Страница https://magicroll.ru/tyumen/supy/tom-iam-lait доступна...
Том ям Лайт собран
...Страница https://magicroll.ru/tyumen/supy/tom-iam-ramen-s-krevetkami доступна...
Том Ям Рамен с креветками собран
...Страница https://magicroll.ru/tyumen/supy/tom-iam-s-kuritsei доступна...
Том ям с курицей собран
...Страница https://magicroll.ru/tyumen/supy/otvarnoi-ris доступна...
Отварной Рис собран
...Страница https://magicroll.ru/tyumen/goriachee-i-vok/vok-ris доступна...
Вок Рис собран
...Страница https://magicroll.ru/tyumen/goriachee-i-vok/chiken-chips доступна...
Чикен Чипс собран
...Страница https://magicroll.ru/tyumen/detskoe-meniu/kombo-trio доступна...
Комбо Трио собран
...Страница https://magicroll.ru/tyumen/detskoe-meniu/kombo-roll-i-napitok доступна...
Комбо Ролл и напиток собран
...Страница https://magicroll.ru/tyumen/detskoe-meniu/kombo-piat-k-odnomu доступна...
Комбо Пять к одному собран
...Страница https://magicroll.ru/tyumen/detskoe-meniu/palochki-khvatalochki-rozovye доступна...
Палочки-хваталочки| Розовые собран
...Страница https://magicroll.ru/tyumen/detskoe-meniu/palochki-khvatalochki-golubye доступна...
Палочки-хваталочки| Голубые собран
...Страница https://magicroll.ru/tyumen/detskoe-meniu/palochki-khvatalochki-biriuzovye доступна...
Палочки-хваталочки| Бирюзовые собран
...Страница https://magicroll.ru/tyumen/detskoe-meniu/naggetsy доступна...
Наггетсы собран
...Страница https://magicroll.ru/tyumen/detskoe-meniu/kurinye-palochki доступна...
Куриные палочки собран
...Страница https://magicroll.ru/tyumen/detskoe-meniu/chiken-chips доступна...
Чикен Чипс собран
...Страница https://magicroll.ru/tyumen/detskoe-meniu/kartofel-fri доступна...
Картофель Фри собран
...Страница https://magicroll.ru/tyumen/detskoe-meniu/roll-maki-kuritsa доступна...
Ролл Маки курица собран
...Страница https://magicroll.ru/tyumen/deserty/moti-tort-mango-marakuiia доступна...
Моти-торт Манго - маракуйя  собран
...Страница https://magicroll.ru/tyumen/deserty/roll-banan-karamel-v-mamenori доступна...
Ролл Банан Карамель в МАМЕНОРИ собран
...Страница https://magicroll.ru/tyumen/deserty/spring-roll-mango-banan доступна...
Спринг ролл Манго Банан собран
...Страница https://magicroll.ru/tyumen/molochnye-kokteili/molochnyi-kokteil-banan доступна...
Молочный коктейль Банан  собран
...Страница https://magicroll.ru/tyumen/molochnye-kokteili/molochnyi-kokteil-vanil доступна...
Молочный коктейль Ваниль собран
...Страница https://magicroll.ru/tyumen/molochnye-kokteili/molochnyi-kokteil-karamel доступна...
Молочный коктейль Карамель  собран
...Страница https://magicroll.ru/tyumen/molochnye-kokteili/molochnyi-kokteil-klubnika доступна...
Молочный коктейль Клубника собран
...Страница https://magicroll.ru/tyumen/molochnye-kokteili/mango-sheik доступна...
Манго шейк собран
...Страница https://magicroll.ru/tyumen/napitki/limonad-klassicheskii доступна...
Лимонад Классический собран
...Страница https://magicroll.ru/tyumen/napitki/limonad-tarkhun доступна...
Лимонад Тархун собран
...Страница https://magicroll.ru/tyumen/napitki/limonad-malina-miata доступна...
Лимонад Малина - мята собран
...Страница https://magicroll.ru/tyumen/napitki/limonad-tropicheskii доступна...
Лимонад Тропический собран
...Страница https://magicroll.ru/tyumen/napitki/mors-chernaia-smorodina доступна...
Морс Черная смородина  собран
...Страница https://magicroll.ru/tyumen/napitki/mors-oblepikha доступна...
Морс Облепиха собран
...Страница https://magicroll.ru/tyumen/dopolneniia/soevyi-sous доступна...
Соевый соус  собран
...Страница https://magicroll.ru/tyumen/dopolneniia/soevyi-sous-1 доступна...
Соевый соус  собран
...Страница https://magicroll.ru/tyumen/dopolneniia/vasabi доступна...
Васаби  собран
...Страница https://magicroll.ru/tyumen/dopolneniia/imbir доступна...
Имбирь собран
...Страница https://magicroll.ru/tyumen/dopolneniia/sous-orekhovyi доступна...
Соус Ореховый собран
...Страница https://magicroll.ru/tyumen/dopolneniia/sous-chili-iudzu доступна...
Соус Чили Юдзу  собран
...Страница https://magicroll.ru/tyumen/dopolneniia/sous-tsezar доступна...
Соус Цезарь  собран
...Страница https://magicroll.ru/tyumen/dopolneniia/sous-poke доступна...
Соус Поке собран
...Страница https://magicroll.ru/tyumen/dopolneniia/sous-teriiaki доступна...
Соус Терияки  собран
...Страница https://magicroll.ru/tyumen/dopolneniia/sous-unagi доступна...
Соус Унаги  собран
...Страница https://magicroll.ru/tyumen/dopolneniia/sous-slivochnyi-chili доступна...
Соус Сливочный Чили  собран
...Страница https://magicroll.ru/tyumen/dopolneniia/ketchup доступна...
Кетчуп собран
...Страница https://magicroll.ru/tyumen/sertifikaty/sertifikat-1000 доступна...
Сертификат 1000₽ собран
...Страница https://magicroll.ru/tyumen/sertifikaty/sertifikat-2000 доступна...
Сертификат 2000₽ собран
...Страница https://magicroll.ru/tyumen/sertifikaty/sertifikat-3000 доступна...
Сертификат 3000₽ собран

In [ ]:
data.reset_index(drop = True).to_pickle("nutrition.pkl")

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_pickle("nutrition.pkl")
data.head()

,name,description,nutrition_facts,url
0,Ролл Филадельфия лайт,Когда хочется чуть меньше рыбы. Только лосось ...,"Калорийность — 191,4 ккал/100 г",https://magicroll.ru/tyumen/rolly/roll-filadel...
1,Ролл Филадельфия лайт,Когда хочется чуть меньше рыбы. Только лосось ...,"Белки — 5,9",https://magicroll.ru/tyumen/rolly/roll-filadel...
2,Ролл Филадельфия лайт,Когда хочется чуть меньше рыбы. Только лосось ...,"Жиры — 9,7",https://magicroll.ru/tyumen/rolly/roll-filadel...
3,Ролл Филадельфия лайт,Когда хочется чуть меньше рыбы. Только лосось ...,"Углеводы — 20,1",https://magicroll.ru/tyumen/rolly/roll-filadel...
4,Ролл Калифорния с креветкой,"Сочетание тигровой креветки, сливочного сыра, ...","Калорийность — 162,8 ккал/100 г",https://magicroll.ru/tyumen/rolly/roll-kalifor...

In [ ]:
data['counter'] = data.groupby(["name", "description", "url"]).cumcount()
res_df = data.pivot(index=["name", "description", "url"], columns='counter', values='nutrition_facts')
res_df.columns = ["calories", "protein", "fat", "carbohydrates"]
res_df = res_df.reset_index()

,name,description,url,calories,protein,fat,carbohydrates
0,Васаби,,https://magicroll.ru/tyumen/dopolneniia/vasabi,"Калорийность — 372,2 ккал/100 г","Белки — 14,5","Жиры — 9,4","Углеводы — 57,4"
1,Вок Рис,"Рис с миксом овощей: хрустящая морковь, болгар...",https://magicroll.ru/tyumen/goriachee-i-vok/vo...,"Калорийность — 143,1 ккал/100 г","Белки — 5,6","Жиры — 2,8","Углеводы — 23,9"
2,Запеченный ролл Лосось Авокадо,"Лосось, сливочный сыр и авокадо, запеченные по...",https://magicroll.ru/tyumen/rolly-zapechionnye...,"Калорийность — 242,5 ккал/100 г","Белки — 7,1","Жиры — 14,6","Углеводы — 20,7"
3,Имбирь,,https://magicroll.ru/tyumen/dopolneniia/imbir,"Калорийность — 62,6 ккал/100 г","Белки — 0,0","Жиры — 0,0","Углеводы — 3,7"
4,Картофель Фри,,https://magicroll.ru/tyumen/detskoe-meniu/kart...,"Калорийность — 161,0 ккал/100 г","Белки — 3,0","Жиры — 5,0","Углеводы — 26,0"
...,...,...,...,...,...,...,...
77,Том Ям Рамен с креветками,Пряный и насыщенный острый бульон в сочетание ...,https://magicroll.ru/tyumen/supy/tom-iam-ramen...,"Калорийность — 214,3 ккал/100 г","Белки — 5,9","Жиры — 11,5","Углеводы — 21,8"
78,Том ям Лайт,Острый и ароматный бульон Том Ям на основе кур...,https://magicroll.ru/tyumen/supy/tom-iam-lait,"Калорийность — 122,0 ккал/100 г","Белки — 1,5","Жиры — 9,9","Углеводы — 6,7"
79,Том ям с курицей,"Острый бульон том ям с курицей, грибами, томат...",https://magicroll.ru/tyumen/supy/tom-iam-s-kur...,"Калорийность — 113,2 ккал/100 г","Белки — 5,0","Жиры — 4,6","Углеводы — 12,9"
80,Чикен Чипс,Курица в хрустящей темпуре на ваш выбор с золо...,https://magicroll.ru/tyumen/detskoe-meniu/chik...,"Калорийность — 272,1 ккал/100 г","Белки — 19,3","Жиры — 1,6","Углеводы — 45,1"
81,Чикен Чипс,Курица в хрустящей темпуре на ваш выбор с золо...,https://magicroll.ru/tyumen/goriachee-i-vok/ch...,"Калорийность — 272,1 ккал/100 г","Белки — 19,3","Жиры — 1,6","Углеводы — 45,1"

In [ ]:
for col in ["calories", "protein", "fat", "carbohydrates"]:
  res_df[col] = res_df[col].str.split("—").str.get(1).str.split().str.get(0).str.replace(",", ".").astype(float)

In [ ]:
res_df = res_df.reset_index(drop = False)
res_df

,name,description,url,calories,protein,fat,carbohydrates
0,Васаби,,https://magicroll.ru/tyumen/dopolneniia/vasabi,372.2,14.5,9.4,57.4
1,Вок Рис,"Рис с миксом овощей: хрустящая морковь, болгар...",https://magicroll.ru/tyumen/goriachee-i-vok/vo...,143.1,5.6,2.8,23.9
2,Запеченный ролл Лосось Авокадо,"Лосось, сливочный сыр и авокадо, запеченные по...",https://magicroll.ru/tyumen/rolly-zapechionnye...,242.5,7.1,14.6,20.7
3,Имбирь,,https://magicroll.ru/tyumen/dopolneniia/imbir,62.6,0.0,0.0,3.7
4,Картофель Фри,,https://magicroll.ru/tyumen/detskoe-meniu/kart...,161.0,3.0,5.0,26.0
...,...,...,...,...,...,...,...
77,Том Ям Рамен с креветками,Пряный и насыщенный острый бульон в сочетание ...,https://magicroll.ru/tyumen/supy/tom-iam-ramen...,214.3,5.9,11.5,21.8
78,Том ям Лайт,Острый и ароматный бульон Том Ям на основе кур...,https://magicroll.ru/tyumen/supy/tom-iam-lait,122.0,1.5,9.9,6.7
79,Том ям с курицей,"Острый бульон том ям с курицей, грибами, томат...",https://magicroll.ru/tyumen/supy/tom-iam-s-kur...,113.2,5.0,4.6,12.9
80,Чикен Чипс,Курица в хрустящей темпуре на ваш выбор с золо...,https://magicroll.ru/tyumen/detskoe-meniu/chik...,272.1,19.3,1.6,45.1
81,Чикен Чипс,Курица в хрустящей темпуре на ваш выбор с золо...,https://magicroll.ru/tyumen/goriachee-i-vok/ch...,272.1,19.3,1.6,45.1

In [ ]:
res_df.to_excel("calories.xlsx")